# Generated by Django 5.2.5 on 2025-08-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_product_type_delete_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
