# Generated by Django 5.2.5 on 2025-08-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
    ]
