# Generated by Django 5.2.5 on 2025-08-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_image_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_primary',
        ),
    ]
