# Generated by Django 5.2.5 on 2025-08-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
