# Generated by Django 5.2.5 on 2025-08-21 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='variant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariant'),
        ),
    ]
