# Generated by Django 5.2.5 on 2025-08-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_listed',
            new_name='is_active',
        ),
    ]
