# Generated by Django 5.2.5 on 2026-02-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
