# Generated by Django 5.2.5 on 2025-09-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_payment_gateway_order_id_payment_gateway_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
