# Generated by Django 5.2.5 on 2025-10-06 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_referral_referred_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred_users',
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_users',
            field=models.ManyToManyField(blank=True, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
