# Generated by Django 5.2.5 on 2025-10-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_remove_referral_referred_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
