# Generated by Django 5.2.5 on 2025-10-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_usercoupon_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-10 01:05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-10 01:05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
