# Generated by Django 5.2.5 on 2025-08-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userOTP',
        ),
    ]
