# Generated by Django 5.2.5 on 2025-10-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_address_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referrel_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
