# Generated by Django 5.2.5 on 2025-10-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
