# Generated by Django 5.2.5 on 2026-02-06 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_unchanged_discount'),
        ('wallet', '0002_wallettransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='order.order'),
        ),
    ]
