# Generated by Django 5.2.5 on 2026-02-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='purpose',
            field=models.CharField(choices=[('order_payment', 'Order Payment'), ('refund', 'Refund'), ('topup', 'Wallet Topup')], default='order_payment', max_length=20),
        ),
    ]
