# Generated by Django 5.2.5 on 2026-02-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallettransaction_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='purpose',
            field=models.CharField(choices=[('order_payment', 'Order Payment'), ('refund', 'Refund'), ('topup', 'Wallet Topup')], default='', max_length=20),
        ),
    ]
