# Generated by Django 5.2.5 on 2025-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
