# Generated by Django 5.2.5 on 2025-09-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
