# Generated by Django 5.2.5 on 2025-09-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_address_phone_number_alter_address_street'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created_at'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
