# Generated by Django 5.2.5 on 2025-10-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_address_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
