# Generated by Django 5.2.5 on 2026-02-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_address_street'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created_at']},
        ),
    ]
