# Generated by Django 5.2.5 on 2026-02-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cart_cartitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={},
        ),
    ]
