# Generated by Django 5.2.5 on 2025-11-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_address_street'),
        ('order', '0006_order_city_order_country_order_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='address.address'),
        ),
    ]
