# Generated by Django 5.2.5 on 2025-11-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
