# Generated by Django 5.2.5 on 2025-11-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_full_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_adress',
            new_name='full_address',
        ),
    ]
