# Generated by Django 5.2.5 on 2025-11-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_full_adress_order_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='admin_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
