# Generated by Django 5.2.5 on 2025-11-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_returned_requested',
            field=models.BooleanField(default=False),
        ),
    ]
