# Generated by Django 5.2.5 on 2025-11-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='order.orderitem'),
        ),
    ]
