# Generated by Django 5.2.5 on 2026-01-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('partialy_returned', 'Partially Returned'), ('failed', 'Failed'), ('out for delivery', 'Out for Delivery')], default='pending', max_length=20),
        ),
    ]
