# Generated by Django 5.2.5 on 2026-02-03 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_unchanged_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unchanged_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
