# Generated by Django 5.2.5 on 2026-02-07 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_address_street'),
        ('offers', '0008_categoryoffer_created_at_categoryoffer_updated_at_and_more'),
        ('order', '0019_order_unchanged_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date', 'status'], name='order_order_order_d_e382ba_idx'),
        ),
    ]
