# Generated by Django 5.2.5 on 2026-02-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_returned_requested',
        ),
    ]
